from pathlib import Path

REPO_FILES = {
    "analysis/02_matrices_pt.Rmd": [
        (
            "Antes da codificação dos marcadores, a tabela seguinte confere a estrutura recebida do Módulo 01: número de indivíduos e características, quantidade de locos antes e depois do controle de qualidade e número de famílias. Ela funciona como ponto de controle entre os módulos; nenhum novo filtro é aplicado nessa conferência.",
            "Antes da codificação dos marcadores, a tabela seguinte confere a estrutura recebida do Módulo 01: número de indivíduos e características, quantidade de locos antes e depois do controle de qualidade e número de famílias. A comparação confirma que o objeto recebido contém a estrutura esperada; nenhum novo filtro é aplicado nessa etapa."
        ),
        (
            "Uma coluna é criada para cada combinação loco–alelo, e chamadas SSR ausentes permanecem como `NA` até a etapa de imputação. Antes de qualquer filtragem de colunas alélicas, as dosagens de todos os alelos de um loco diploide somam 2 para cada genótipo observado. Essa propriedade será usada posteriormente como diagnóstico da codificação.\n",
            "Uma coluna é criada para cada combinação loco–alelo, e chamadas SSR ausentes permanecem como `NA` até a etapa de imputação. Antes de qualquer filtragem de colunas alélicas, as dosagens de todos os alelos de um loco diploide somam 2 para cada genótipo observado. Essa propriedade será usada posteriormente como diagnóstico da codificação.\n\nA codificação é construída em etapas que correspondem diretamente às operações do código:\n\n1. **Seleção dos locos mantidos.** `locus_audit_full$Locus[locus_audit_full$Keep_locus]` usa o vetor lógico `Keep_locus` para recuperar somente os nomes aprovados no controle de qualidade. Em seguida, `ssr_raw[, retained_loci_full, drop = FALSE]` mantém todas as linhas e apenas essas colunas; `drop = FALSE` preserva a estrutura matricial mesmo quando a seleção contém poucas colunas.\n2. **Separação dos dois alelos do código SSR.** Para um código como `12`, `floor(codes / 10)` retorna o algarismo das dezenas, isto é, o primeiro alelo (`1`). O operador `%%` devolve o resto da divisão inteira; assim, `codes %% 10` retorna o algarismo das unidades, correspondente ao segundo alelo (`2`).\n3. **Contagem das cópias de cada alelo.** As comparações `allele_1 == allele` e `allele_2 == allele` indicam se o alelo está presente em cada posição. `as.numeric()` converte `TRUE` em 1 e `FALSE` em 0; a soma das duas posições produz a dosagem 0, 1 ou 2. Quando o código SSR é ausente, a dosagem é mantida como `NA`.\n4. **Montagem da matriz.** Cada vetor de dosagem é armazenado em uma lista. Ao final, `do.call(cbind, dosage_parts_full)` combina esses vetores como colunas de uma única matriz, enquanto `bind_rows(allele_map_parts_full)` reúne os metadados que ligam cada coluna ao loco e ao alelo de origem.\n"
        ),
        (
            "# Exemplo das dosagens obtidas.\ndosage_full_raw[1:6, 1:8]",
            "# Mostra uma prévia das colunas de dosagem obtidas.\nas.data.frame(dosage_full_raw[1:6, 1:8]) |>\n  tabela_html(caption = \"Prévia das dosagens alélicas\")"
        ),
        (
            "São mantidas colunas com frequência entre 0,05 e 0,95 e desvio-padrão de dosagem positivo. Os limites inferior e superior são simétricos: removem alelos muito raros e colunas praticamente fixadas, enquanto `Dosage_sd > 0` garante variação observável. O filtro atua sobre colunas de dosagem alélica; ele não remove indivíduos.\n",
            "São mantidas colunas com frequência entre 0,05 e 0,95 e desvio-padrão de dosagem positivo. Os limites inferior e superior são simétricos: removem alelos muito raros e colunas praticamente fixadas, enquanto `Dosage_sd > 0` garante variação observável. O filtro atua sobre colunas de dosagem alélica; ele não remove indivíduos.\n\nNo código, `colMeans(dosage_full_raw, na.rm = TRUE) / 2` calcula simultaneamente a frequência de todas as colunas: `na.rm = TRUE` exclui chamadas ausentes do cálculo da média e a divisão por 2 converte a dosagem média, que varia de 0 a 2, em frequência alélica entre 0 e 1. O laço com `sd(..., na.rm = TRUE)` calcula o desvio-padrão de cada coluna. Por fim, `is.finite()` impede que resultados não finitos sejam aceitos antes de aplicar os limites de frequência e a condição `Dosage_sd > 0`.\n"
        ),
        (
            "As dosagens ausentes são substituídas pela média da respectiva coluna calculada no painel genotípico completo. Como a mesma média é subtraída na centralização, uma dosagem imputada pela média passa a valer exatamente zero em `M`: ela representa ausência de desvio em relação à frequência média da coluna, e não uma nova classe genotípica.\n\nA matriz resultante é denotada por \\(\\mathbf M\\). Suas colunas são centralizadas, mas não padronizadas para variância unitária. Como definido no objetivo, a imputação usa somente informação genotípica dos 150 candidatos; nenhum fenótipo de validação entra no cálculo.\n",
            "As dosagens ausentes são substituídas pela média da respectiva coluna calculada no painel genotípico completo. `marker_means_full <- colMeans(dosage_full, na.rm = TRUE)` calcula uma média para cada coluna. Dentro do laço, `is.na(dosage_full_imputed[, j])` identifica as posições ausentes da coluna `j`, que recebem `marker_means_full[j]`.\n\nDepois da imputação, `sweep(dosage_full_imputed, 2, marker_means_full, FUN = \"-\")` centraliza as dosagens. O argumento `2` indica que a operação é feita por colunas, e `FUN = \"-\"` subtrai de cada valor a média correspondente. Como a mesma média foi usada na imputação, uma dosagem imputada passa a valer exatamente zero em `M`: ela representa ausência de desvio em relação à frequência média da coluna, e não uma nova classe genotípica.\n\nA matriz resultante é denotada por \\(\\mathbf M\\). Suas colunas são centralizadas, mas não padronizadas para variância unitária. A imputação utiliza somente informação genotípica dos 150 candidatos; nenhum fenótipo de validação entra no cálculo.\n"
        ),
        (
            "\\[\n\\mathbf G =\n\\frac{\\mathbf M\\mathbf M^{\\mathsf T}}\n{\\sum_j 2p_j(1-p_j)}.\n\\]\n",
            "\\[\n\\mathbf G =\n\\frac{\\mathbf M\\mathbf M^{\\mathsf T}}\n{\\sum_j 2p_j(1-p_j)}.\n\\]\n\nNo código, `allele_frequencies_full <- marker_means_full / 2` recupera \\(p_j\\) porque a média da dosagem corresponde a \\(2p_j\\). `tcrossprod(M_full)` calcula diretamente \\(\\mathbf M\\mathbf M^{\\mathsf T}\\), isto é, um produto entre indivíduos a partir das colunas centralizadas. A divisão por `denominator_full` aplica a escala definida na fórmula. Depois, `(G_full + t(G_full)) / 2` remove apenas pequenas diferenças numéricas entre elementos simétricos, e `eigen(..., symmetric = TRUE, only.values = TRUE)` obtém os autovalores usados no diagnóstico de semidefinição positiva.\n"
        ),
        (
            "Os 150 indivíduos são divididos em cinco grupos de validação de 30 indivíduos. O algoritmo percorre uma família por vez: embaralha seus membros, ordena os folds pela carga total já acumulada, usa uma ordem aleatória apenas para desempatar cargas iguais, distribui os membros da família ciclicamente entre esses folds e atualiza a carga global. Esse procedimento combina dois objetivos: espalhar cada família entre os folds e manter os tamanhos totais equilibrados.\n",
            "Os 150 indivíduos são divididos em cinco grupos de validação de 30 indivíduos. A construção é feita família por família e pode ser acompanhada diretamente pelas funções usadas no código:\n\n1. `which(family == family_level)` localiza os indivíduos da família atual e `sample()` embaralha suas posições.\n2. `seq_len(N_FOLDS)` gera os números dos cinco folds. Uma segunda chamada a `sample()` cria uma ordem aleatória usada somente para desempatar folds com a mesma carga acumulada.\n3. `order(fold_load, match(seq_len(N_FOLDS), random_tie_order))` prioriza primeiro os folds menos preenchidos e usa a ordem aleatória apenas quando duas cargas são iguais.\n4. `rep(ordered_folds, length.out = length(family_indices))` repete ciclicamente essa ordem até produzir um rótulo de fold para cada membro da família.\n5. `tabulate(family_labels, nbins = N_FOLDS)` conta quantos indivíduos acabaram de ser enviados a cada fold e atualiza `fold_load`.\n\nEsse procedimento espalha os membros de cada família entre os folds ao mesmo tempo que mantém os tamanhos totais equilibrados.\n"
        ),
        (
            "No conjunto de dados analisado, as 72 colunas de dosagem não representam 72 dimensões independentes. O diagnóstico compara o posto observado de `M` com `sum(k_l - 1)`, em que `k_l` é o número de colunas alélicas mantidas no loco `l`; também verifica se a soma das dosagens por loco continua igual a 2, se a centralização de `M` é numericamente correta e se `G` pode ser reconstruída a partir de `M` e do mesmo denominador. Simetria, posto, diagonal e menor autovalor completam a checagem numérica de `G`.\n",
            "No conjunto de dados analisado, as 72 colunas de dosagem não representam 72 dimensões independentes. O posto teórico é calculado por `sum(table(...)- 1L)`: `table()` conta quantas colunas alélicas foram mantidas em cada loco, subtrair 1 fornece \\(k_l-1\\) para cada loco e `sum()` reúne essas contribuições. O posto observado de `M` é então comparado a esse valor.\n\nA propriedade diploide é verificada loco a loco com `rowSums(...) - 2`: `rowSums()` soma as dosagens alélicas mantidas de cada indivíduo e a diferença em relação a 2 deve ser numericamente nula. A centralização é verificada pelas médias das colunas de `M`, e `tcrossprod(M_full) / denominator_full` reconstrói `G` para comparação com a matriz armazenada. Simetria, posto, diagonal e menor autovalor completam a checagem numérica de `G`.\n"
        ),
        ("  # Lista os valores correspondentes aos itens da tabela.\n", ""),
        ("# Constrói o gráfico usado na interpretação.\n", ""),
        ("  # Lista os itens verificados no inventário das matrizes.\n", ""),
        ("# Exibe o inventário numérico das matrizes.\n", "")
    ],
    "analysis/02_matrices_en.Rmd": [
        (
            "Before marker coding, the following table checks the structure received from Module 01: numbers of individuals and traits, loci before and after quality control, and families. It acts as a checkpoint between modules; no new filter is applied in this check.",
            "Before marker coding, the following table checks the structure received from Module 01: numbers of individuals and traits, loci before and after quality control, and families. The comparison confirms that the input object has the expected structure; no new filter is applied at this stage."
        ),
        (
            "One column is created for every locus–allele combination, and missing SSR calls remain `NA` until imputation. Before any allele-column filtering, dosages across all alleles at a diploid locus sum to 2 for every observed genotype. This property is later used as a coding diagnostic.\n",
            "One column is created for every locus–allele combination, and missing SSR calls remain `NA` until imputation. Before any allele-column filtering, dosages across all alleles at a diploid locus sum to 2 for every observed genotype. This property is later used as a coding diagnostic.\n\nThe coding follows a sequence that maps directly to the operations in the code:\n\n1. **Select retained loci.** `locus_audit_full$Locus[locus_audit_full$Keep_locus]` uses the logical vector `Keep_locus` to recover only locus names that passed quality control. Then `ssr_raw[, retained_loci_full, drop = FALSE]` keeps every row and only those columns; `drop = FALSE` preserves a two-dimensional structure even when few columns are selected.\n2. **Separate the two alleles in an SSR code.** For a code such as `12`, `floor(codes / 10)` returns the tens digit, the first allele (`1`). The `%%` operator returns the remainder of integer division, so `codes %% 10` returns the units digit, the second allele (`2`).\n3. **Count copies of each allele.** The comparisons `allele_1 == allele` and `allele_2 == allele` indicate whether the allele occurs in each position. `as.numeric()` converts `TRUE` to 1 and `FALSE` to 0; summing both positions yields dosage 0, 1, or 2. If the SSR code is missing, dosage remains `NA`.\n4. **Assemble the matrix.** Each dosage vector is stored in a list. At the end, `do.call(cbind, dosage_parts_full)` combines these vectors as columns of one matrix, while `bind_rows(allele_map_parts_full)` combines the metadata linking each column to its source locus and allele.\n"
        ),
        (
            "# Example of the resulting dosage columns.\ndosage_full_raw[1:6, 1:8]",
            "# Display a preview of the resulting dosage columns.\nas.data.frame(dosage_full_raw[1:6, 1:8]) |>\n  format_table(caption = \"Preview of allele dosages\")"
        ),
        (
            "Columns are retained when frequency lies between 0.05 and 0.95 and dosage standard deviation is positive. The lower and upper limits are symmetric: they remove very rare alleles and nearly fixed columns, while `Dosage_sd > 0` guarantees observed variation. The filter acts on allele-dosage columns; it does not remove individuals.\n",
            "Columns are retained when frequency lies between 0.05 and 0.95 and dosage standard deviation is positive. The lower and upper limits are symmetric: they remove very rare alleles and nearly fixed columns, while `Dosage_sd > 0` guarantees observed variation. The filter acts on allele-dosage columns; it does not remove individuals.\n\nIn the code, `colMeans(dosage_full_raw, na.rm = TRUE) / 2` computes frequencies for all columns at once: `na.rm = TRUE` excludes missing calls from the mean, and division by 2 converts mean dosage, which ranges from 0 to 2, into allele frequency between 0 and 1. The loop with `sd(..., na.rm = TRUE)` computes the standard deviation of each column. Finally, `is.finite()` prevents non-finite results from being accepted before the frequency limits and `Dosage_sd > 0` condition are applied.\n"
        ),
        (
            "Missing dosages are replaced by the mean of the corresponding column computed from the full genotype panel. Because the same mean is subtracted during centering, a mean-imputed dosage becomes exactly zero in `M`: it represents no deviation from the column average rather than a new genotype class.\n\nThe resulting matrix is denoted by \\(\\mathbf M\\). Its columns are centered but are not standardized to unit variance. As defined in the objective, imputation uses genotype information from all 150 candidates; no validation phenotype enters this calculation.\n",
            "Missing dosages are replaced by the mean of the corresponding column computed from the full genotype panel. `marker_means_full <- colMeans(dosage_full, na.rm = TRUE)` computes one mean per column. Inside the loop, `is.na(dosage_full_imputed[, j])` identifies missing positions in column `j`, which receive `marker_means_full[j]`.\n\nAfter imputation, `sweep(dosage_full_imputed, 2, marker_means_full, FUN = \"-\")` centers the dosages. The argument `2` specifies a column-wise operation, and `FUN = \"-\"` subtracts the corresponding mean from every value. Because the same mean was used for imputation, a mean-imputed dosage becomes exactly zero in `M`: it represents no deviation from the column average rather than a new genotype class.\n\nThe resulting matrix is denoted by \\(\\mathbf M\\). Its columns are centered but are not standardized to unit variance. Imputation uses genotype information from all 150 candidates; no validation phenotype enters this calculation.\n"
        ),
        (
            "\\[\n\\mathbf G =\n\\frac{\\mathbf M\\mathbf M^{\\mathsf T}}\n{\\sum_j 2p_j(1-p_j)}.\n\\]\n",
            "\\[\n\\mathbf G =\n\\frac{\\mathbf M\\mathbf M^{\\mathsf T}}\n{\\sum_j 2p_j(1-p_j)}.\n\\]\n\nIn the code, `allele_frequencies_full <- marker_means_full / 2` recovers \\(p_j\\) because mean dosage equals \\(2p_j\\). `tcrossprod(M_full)` directly computes \\(\\mathbf M\\mathbf M^{\\mathsf T}\\), a product among individuals based on the centered columns. Dividing by `denominator_full` applies the scale defined in the equation. Then `(G_full + t(G_full)) / 2` removes only small numerical differences between symmetric elements, and `eigen(..., symmetric = TRUE, only.values = TRUE)` obtains the eigenvalues used to diagnose positive semidefiniteness.\n"
        ),
        (
            "The 150 individuals are divided into five validation groups of 30 individuals. The algorithm processes one family at a time: it shuffles family members, orders folds by their current total load, uses a random order only to break ties between equally loaded folds, cycles family members across those folds, and then updates the global load. This combines two goals: spreading each family across folds and keeping total fold sizes balanced.\n",
            "The 150 individuals are divided into five validation groups of 30 individuals. The construction proceeds family by family and can be followed directly through the functions used in the code:\n\n1. `which(family == family_level)` locates individuals from the current family, and `sample()` shuffles their positions.\n2. `seq_len(N_FOLDS)` generates the five fold numbers. A second `sample()` call creates a random order used only to break ties among folds with equal accumulated load.\n3. `order(fold_load, match(seq_len(N_FOLDS), random_tie_order))` prioritizes less-filled folds first and uses the random order only when two loads are equal.\n4. `rep(ordered_folds, length.out = length(family_indices))` cycles through this order until one fold label is produced for every family member.\n5. `tabulate(family_labels, nbins = N_FOLDS)` counts how many individuals were just assigned to each fold and updates `fold_load`.\n\nThis procedure spreads members of each family across folds while keeping total fold sizes balanced.\n"
        ),
        (
            "In the analyzed dataset, the 72 dosage columns do not represent 72 independent dimensions. The diagnostic compares the observed rank of `M` with `sum(k_l - 1)`, where `k_l` is the number of retained allele columns at locus `l`; it also checks whether within-locus dosage still sums to 2, whether `M` is numerically centered, and whether `G` can be reconstructed from `M` and the same denominator. Symmetry, rank, diagonal, and smallest eigenvalue complete the numerical check of `G`.\n",
            "In the analyzed dataset, the 72 dosage columns do not represent 72 independent dimensions. The theoretical rank is computed by `sum(table(...) - 1L)`: `table()` counts retained allele columns at each locus, subtracting 1 gives \\(k_l-1\\) for each locus, and `sum()` combines those contributions. The observed rank of `M` is then compared with that value.\n\nThe diploid property is checked locus by locus with `rowSums(...) - 2`: `rowSums()` adds the retained allele dosages for each individual, and the difference from 2 should be numerically zero. Centering is checked through the column means of `M`, and `tcrossprod(M_full) / denominator_full` reconstructs `G` for comparison with the stored matrix. Symmetry, rank, diagonal, and smallest eigenvalue complete the numerical check of `G`.\n"
        ),
        ("  # List the values corresponding to the table entries.\n", ""),
        ("# Build the figure used for interpretation.\n", ""),
        ("  # List the items checked in the matrix inventory.\n", ""),
        ("# Display the numerical inventory of the matrices.\n", "")
    ]
}

for filename, replacements in REPO_FILES.items():
    path = Path(filename)
    text = path.read_text(encoding="utf-8")
    for old, new in replacements:
        count = text.count(old)
        if count < 1:
            raise SystemExit(f"{filename}: target not found: {old[:120]!r}")
        text = text.replace(old, new)
    path.write_text(text, encoding="utf-8")

print("Module 02 didactic replacements applied successfully.")
