from pathlib import Path

replacements = {
"analysis/02_matrices_pt.Rmd": [
("O resumo de `M` verifica quatro propriedades básicas. O número de linhas deve coincidir com os 150 candidatos; o número de colunas corresponde às dosagens alélicas retidas; o posto revela as dependências lineares entre colunas; e a máxima média absoluta deve ficar próxima de zero, confirmando a centralização numérica.", "O resumo de `M` verifica quatro propriedades básicas. O número de linhas deve coincidir com os 150 candidatos; o número de colunas corresponde às dosagens alélicas retidas; o posto revela as dependências lineares entre colunas; e a máxima média absoluta deve ficar próxima de zero, confirmando a centralização numérica. A expressão `qr(M_full)$rank` obtém o posto a partir da decomposição QR: esse valor representa o número de direções linearmente independentes presentes nas colunas de `M`."),
("Esse procedimento espalha os membros de cada família entre os folds ao mesmo tempo que mantém os tamanhos totais equilibrados.\n\nA semente fixa preserva exatamente a mesma partição entre execuções.", "Esse procedimento espalha os membros de cada família entre os folds ao mesmo tempo que mantém os tamanhos totais equilibrados. Depois da alocação, `apply(family_fold_table, 1, max)` e `apply(family_fold_table, 1, min)` calculam, para cada linha da tabela — isto é, para cada família — as maiores e menores contagens entre folds. O argumento `1` indica operação por linhas; a diferença entre máximo e mínimo forma `family_balance`.\n\nA semente fixa preserva exatamente a mesma partição entre execuções."),
("A tabela abaixo mostra as primeiras atribuições após ordenar por fold, família e indivíduo. Ela serve apenas para tornar a estrutura de `cv_folds` concreta: a coluna `Fold` é a única informação usada no Módulo 03 para decidir quais fenótipos serão mascarados em cada rodada.\n", "A expressão `cv_folds |> arrange(Fold, FAM, IND) |> head(15)` ordena a tabela primeiro por fold, depois por família e por identificador, e mantém as 15 primeiras linhas. `arrange()` define essa ordem e `head(15)` limita apenas a prévia apresentada; o objeto `cv_folds` continua contendo os 150 indivíduos. A coluna `Fold` é a informação usada no Módulo 03 para decidir quais fenótipos serão mascarados em cada rodada.\n"),
("A prévia mostra apenas 15 linhas ordenadas para facilitar a inspeção. A tabela completa `cv_folds` mantém os 150 indivíduos e será usada diretamente no Módulo 03.", "As 15 linhas exibidas permitem verificar a estrutura da atribuição sem modificar `cv_folds`, que mantém os 150 indivíduos e será usado diretamente no Módulo 03."),
("O arquivo `matrices_object.rds` é a interface principal com o Módulo 03: reúne matrizes, fenótipos alinhados, metadados, frequências, folds e parâmetros em um único objeto com suas classes preservadas. Os CSVs são saídas de inspeção para consultar a alocação dos folds, o resumo dos tamanhos amostrais, a auditoria das colunas alélicas e o inventário numérico sem precisar abrir o RDS.", "O arquivo `matrices_object.rds` reúne matrizes, fenótipos alinhados, metadados, frequências, folds e parâmetros em um único objeto com suas classes preservadas. `saveRDS()` grava essa lista em um arquivo que pode ser recuperado integralmente com `readRDS()` no Módulo 03. As chamadas `write.csv(..., row.names = FALSE)` exportam as tabelas de folds, frequências e diagnósticos em formato tabular; `row.names = FALSE` evita acrescentar uma coluna artificial com os números das linhas.")
],
"analysis/02_matrices_en.Rmd": [
("The summary of `M` checks four basic properties. Its row count should match the 150 candidates; its column count is the number of retained allele-dosage columns; its rank reveals linear dependencies among columns; and the maximum absolute column mean should be close to zero, confirming numerical centering.", "The summary of `M` checks four basic properties. Its row count should match the 150 candidates; its column count is the number of retained allele-dosage columns; its rank reveals linear dependencies among columns; and the maximum absolute column mean should be close to zero, confirming numerical centering. The expression `qr(M_full)$rank` obtains rank from the QR decomposition: this value is the number of linearly independent directions represented by the columns of `M`."),
("This procedure spreads members of each family across folds while keeping total fold sizes balanced.\n\nThe fixed seed preserves exactly the same partition across executions.", "This procedure spreads members of each family across folds while keeping total fold sizes balanced. After allocation, `apply(family_fold_table, 1, max)` and `apply(family_fold_table, 1, min)` compute, for each row of the table — that is, for each family — the largest and smallest counts across folds. The argument `1` specifies a row-wise operation; the difference between maximum and minimum forms `family_balance`.\n\nThe fixed seed preserves exactly the same partition across executions."),
("The table below displays the first assignments after sorting by fold, family, and individual. It simply makes the structure of `cv_folds` concrete: the `Fold` column is the only information Module 03 uses to decide which phenotypes are masked in each validation round.\n", "The expression `cv_folds |> arrange(Fold, FAM, IND) |> head(15)` sorts the table first by fold, then by family and individual identifier, and retains the first 15 rows. `arrange()` defines this order and `head(15)` limits only the displayed preview; the `cv_folds` object still contains all 150 individuals. The `Fold` column is the information Module 03 uses to decide which phenotypes are masked in each validation round.\n"),
("The preview shows only 15 sorted rows to facilitate inspection. The complete `cv_folds` table retains all 150 individuals and is used directly in Module 03.", "The 15 displayed rows make the allocation structure visible without modifying `cv_folds`, which retains all 150 individuals and is used directly in Module 03."),
("The `matrices_object.rds` file is the primary interface with Module 03: it gathers matrices, aligned phenotypes, metadata, frequencies, folds, and parameters in one object while preserving their classes. The CSV files are inspection-oriented outputs for checking fold allocation, sample-size summaries, allele-column audits, and the numerical inventory without opening the RDS object.", "The `matrices_object.rds` file gathers matrices, aligned phenotypes, metadata, frequencies, folds, and parameters in one object while preserving their classes. `saveRDS()` writes this list to a file that can be recovered intact with `readRDS()` in Module 03. The `write.csv(..., row.names = FALSE)` calls export fold, frequency, and diagnostic tables in tabular form; `row.names = FALSE` prevents an artificial row-number column from being added.")
]
}

for fn, reps in replacements.items():
    p = Path(fn)
    text = p.read_text(encoding='utf-8')
    for old, new in reps:
        n = text.count(old)
        if n != 1:
            raise SystemExit(f'{fn}: expected one target, found {n}: {old[:120]}')
        text = text.replace(old, new, 1)
    p.write_text(text, encoding='utf-8')
print('Corrected final Module 02 explainability refinements applied.')
